### ISSUE TITLE
Issue with (x) dismiss button on replying or starting a new discusiion

### ISSUE THREAD

**Issue by ahmedshiboub** [irmmr/flarum-ext-rtl#1]
the is a problem on mobile view only and it is that when i reply or start a new discussion the x button to dismiss the popup is not clickable
![IMG_20220427_180111](https://user-images.githubusercontent.com/24685204/166072815-28dab41e-7565-45f3-86f0-6acad9815cd1.jpg)

**Comment by irmmr** [comment]
It's fixed now.
Please check here: https://discuss.flarum.org/d/29660-rtl-support/10

Of course, before seeing this issue, I saw your reply in the Flarum.
