### ISSUE TITLE
search icon problem?

### ISSUE THREAD

**Issue by ahmedshiboub** [irmmr/flarum-ext-rtl#2]
hello,
Search icon on desktop view only does not appear at all.
 With RTL
)
![IMG_20220506_221928](https://user-images.githubusercontent.com/24685204/167211139-8990b97d-c524-4c06-ba9a-4d9b9a29ff16.jpg)
 without RTL
![IMG_20220506_221808](https://user-images.githubusercontent.com/24685204/167211331-85d89e3f-f0ce-494d-93c0-67748082237c.jpg)
And thanks for your effort💙

**Comment by irmmr** [comment]
Hi, you’re welcome. Check now, the problem should be fixed.
```shell
composer require irmmr/flarum-ext-rtl:dev-main
php flarum cache:clear
```

**Comment by ahmedshiboub** [comment]
Perfect👏👏
