### ISSUE TITLE
Publish new version of the extension

### ISSUE THREAD

**Issue by SKevo18** [irmmr/flarum-ext-rtl#6]
It appears that there have been a few fixes since the latest v0.1.4 release, which have been pushed 2 years ago. Most notably, the issue with the discussion page having unnecessary margin has been fixed in this commit:

https://github.com/irmmr/flarum-ext-rtl/commit/0dd8d8ef1e1e4793dee5cfc29dd5dd22741bcfe4#diff-faf19bb45897c9cdff224e145ade10d31c89d0128924548229df494eead132afL12

Could you please publish latest release of this extension so that these fixes are applied? It seems that after 2 years, they have matured enough to make a proper extension release.

**Comment by irmmr** [comment]
Hello, since I hadn't updated my own Flarum, I completely lost track of this extension. I tried to make the extension compatible with the latest version of Flarum, which is 1.8.8. I hope it can help.

**Comment by SKevo18** [comment]
> Hello, since I hadn't updated my own Flarum, I completely lost track of this extension. I tried to make the extension compatible with the latest version of Flarum, which is 1.8.8. I hope it can help.

Thanks, I will update the extension
